repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black
        exclude: (dist|json|data|data_format)/
        description: 'Black: The uncompromising Python code formatter'
        entry: black
        # args: ['--check']
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8
        exclude: (dist|json|data|data_format)/
        description: 'Enforce style consistency'
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        description: 'Sort your imports'
        exclude: (dist|json|data|data_format)/
        args: ['--profile', 'black']
        # args: ['--check-only']
  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.5.0
  #   hooks:
  #     - id: interrogate
  #       name: interrogate
  #       exclude: (dist|json|data|data_format)/
  #       description: 'Checks code base for missing docstrings'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        description: Prevents commit of files > 2 MB
        args: ['--maxkb=2000']
      - id: trailing-whitespace