# base docker file, only to be used locally (should not be pushed)
ARG BASE_IMAGE=python:3.10-slim
FROM $BASE_IMAGE

# install project requirements
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && rm -f /tmp/requirements.txt

COPY . /app
WORKDIR /app
