variables:
  # - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'main' branch: PRD environment
  #     - template: ../../config-infra-prod.yml
  # - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'develop' or feature branches: DEV environment
  #     - template: ../../config-infra-dev.yml
  - template: ../../config-infra-prod.yml
  - name: bicepFile
    value: "$(Pipeline.Workspace)/.pipelines/infrastructure/main.bicep"

trigger:
  - none

pool:
  vmImage: $(ap_vm_image)

stages:
  - stage: Lint
    displayName: Lint and Preflight check
    jobs:
      - job: LintBicep
        displayName: Lint Bicep Code
        steps:
          - checkout: self
          - template: ../../templates/lint-bicep.yml
            parameters:
              bicepFile: $(bicepFile)
  - stage: PreflightValidation
    jobs:
      - job: ValidateBicepCode
        displayName: Validate Bicep Code (Rg level)
        steps:
          - task: AzureCli@2
            name: RunPreflightValidateion
            displayName: Run Preflight Validation
            inputs:
              azureSubscription: $(ado_service_connection_rg)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              # inlineScript: |
              #   az deployment sub validate \
              #   --name $(Build.DefinitionName) \
              #   --template-file $(bicepFile) \
              #   --location $(location) \
              #   --parameters location=$(location) prefix=$(namespace) postfix=$(postfix) env=$(environment)
              inlineScript: |
                az deployment group validate \
                  --resource-group $(resource_group) \
                  --name $(Build.DefinitionName) \
                  --template-file $(bicepFile) \
                  --parameters location=$(location) namespace=$(namespace) \
                        environement=$(environment) resource_group=$(resource_group) \
                        aml_workspace=$(aml_workspace) application_insights=$(application_insights) \
                        key_vault=$(key_vault) container_registry=$(container_registry) \
                        storage_account=$(storage_account)
  - stage: CheckOutBicepAndDeploy
    displayName: Deploy Bicep resources
    jobs:
      - deployment: DevDeployBicep
        displayName: Deploy Bicep (Rg level)
        pool:
          vmImage: $(ap_vm_image)
        environment: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: Running ${{ variables.environment }} Deployment
                  inputs:
                    azureSubscription: $(ado_service_connection_rg)
                    scriptType: bash
                    scriptLocation: inlineScript
                    # inlineScript: |
                    #   az --version
                    #   echo "deploying bicep..."
                    #   az deployment sub create \
                    #     --name $(Build.DefinitionName) \
                    #     --location $(location) \
                    #     --template-file $(bicepFile) \
                    #     --parameters location=$(location) prefix=$(namespace) postfix=$(postfix) env=$(environment)
                    inlineScript: |
                      az --version
                      echo "deploying bicep..."
                      az deployment group create \
                        --resource-group $(resource_group) \
                        --name $(Build.DefinitionName) \
                        --template-file $(bicepFile) \
                        --parameters location=$(location) namespace=$(namespace) \
                        environement=$(environment) resource_group=$(resource_group) \
                        aml_workspace=$(aml_workspace) application_insights=$(application_insights) \
                        key_vault=$(key_vault) container_registry=$(container_registry) \
                        storage_account=$(storage_account)
