# template (at the job level, not the step level) to install and cache requirements.

parameters:
  - name: pythonVersion
    type: string
    default: "3.10" # Default Python version
  - name: requirementsFilePath
    type: string
    default: "requirements.txt" # Default requirements file path

jobs:
  - job: CheckCache
    steps:
      - script: |
          requirements_hash=$(sha256sum $(parameters.requirementsFilePath) | cut -d' ' -f1)
          echo "Requirements file hash: $requirements_hash"
          echo "##vso[task.setvariable variable=requirementsHash;isOutput=true]$requirements_hash"
        displayName: Calculate Requirements File Hash

      - script: |
          current_requirements_hash="$(requirementsHash)"
          cached_requirements_hash="$(cat cached_requirements_hash.txt)"

          if [ "$current_requirements_hash" == "$cached_requirements_hash" ]; then
              echo "Cache hit! Requirements file unchanged. Restoring dependencies from cache."
              echo "##vso[task.setvariable variable=cacheHit;isOutput=true]true"
          else
              echo "Cache miss! Requirements file changed. Installing dependencies."
              echo "##vso[task.setvariable variable=cacheHit;isOutput=true]false"
          fi
          echo "$current_requirements_hash" > cached_requirements_hash.txt
        displayName: Check Cache Status

  - job: InstallRequirements
    dependsOn: CheckCache
    steps:
      - ${{ if eq(variables.cacheHit, 'false') }}:
        - script: |
            echo "Installing Python requirements..."
            pip install -r ${{ parameters.requirementsFilePath }}
            echo "Installed Python requirements."
          displayName: Install Python Requirements

  - job: CacheRequirements
    dependsOn: InstallRequirements
    steps:
      - script: |
          echo "Caching Python dependencies..."
          echo "##vso[task.setvariable variable=CacheRequirementsHash;isOutput=true]$(variables.requirementsHash)"
        displayName: Cache Dependencies
