# template (at the job level, not the step level) to install and cache requirements.

parameters:
  - name: pythonVersion
    type: string
    default: "3.10" # Default Python version
  - name: requirementsFilePath
    type: string
    default: "requirements.txt" # Default requirements file path

jobs:
  - job: CheckCache
    steps:
      - script: |
          requirements_hash=$(sha256sum $(parameters.requirementsFilePath) | cut -d' ' -f1)
          echo "Requirements file hash: $requirements_hash"
          echo "##vso[task.setvariable variable=requirementsHash;isOutput=true]$requirements_hash"
        displayName: Calculate Requirements File Hash

  - job: InstallRequirements
    dependsOn: CheckCache
    steps:
      - ${{ if eq(dependencies.CheckCache.outputs['requirementsHash'], variables.requirementsHash) }}:
        - script: echo "Cache hit! Requirements file unchanged. Restoring dependencies from cache."
          displayName: Cache Hit
      - ${{ if ne(dependencies.CheckCache.outputs['requirementsHash'], variables.requirementsHash) }}:
        - script: |
            echo "Cache miss! Requirements file changed. Installing dependencies."
            pip install -r $(parameters.requirementsFilePath)
            echo "Installed Python requirements."
          displayName: Install Python Requirements

  - job: CacheRequirements
    dependsOn: InstallRequirements
    steps:
      - script: |
          echo "Caching Python dependencies..."
          echo "##vso[task.setvariable variable=CacheRequirementsHash;isOutput=true]$(variables.requirementsHash)"
        displayName: Cache Dependencies
