name: CreateCpuDevCluster
pr: none
trigger: none

variables:
  - group: mlops-vg

stages:
  - stage: "Dev"
    displayName: "Dev"
    jobs:
      - job: "CreateCpuDevCluster"
        displayName: "Create the azure ml compute cluster for cpu workloads"
        pool:
          vmImage: "ubuntu-latest"
        timeoutInMinutes: 0

        steps:
          - task: AzureCLI@2
            displayName: "install ml ext"
            inputs:
              azureSubscription: "AzureMlopsRG-Devops-Connector"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: "az extension add -n ml"

          - task: AzureCLI@2
            displayName: "Create / Update the cluster"
            inputs:
              azureSubscription: "AzureMlopsRG-Devops-Connector"
              scriptType: bash
              scriptPath: "$(System.DefaultWorkingDirectory)/infrastructure/aml_compute_clusters/create-dev-cluster.bash"
              arguments: "$(AZURE_RG) $(AZUREML_WORKSPACE)"
              workingDirectory: "$(System.DefaultWorkingDirectory)/infrastructure/aml_compute_clusters"
