# aditional dependendies for creating an environment for cpu workloads
dependencies:
  - python==3.10.11
  - pip=23.2.1

  - pip:
      - azureml-core~=1.52.0
      - azureml-mlflow~=1.52.0
      - kedro~=0.18.13
      - kedro-azureml>=0.6.0
      - kedro-docker~=0.3.1
      - kedro-mlflow~=0.11.9
      - matplotlib~=3.7.2
      - mlflow~=2.5.0
      - nbstripout
      - numpy~=1.23.5
      - numpyencoder
      - optuna~=3.2.0
      - pandas~=2.0.3
      - scikit-learn~=1.3.0
      - seaborn~=0.12.2
      # - torch
