$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: mlops-tpl-train-env-gpu
# check https://github.com/Azure/AzureML-Containers to see all microsoft images
image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04 # gpu image
conda_file: ./train_env_gpu_conda_dependencies.yml
description: >
  Environment created from a Docker image plus Conda environment, optimised for gpu
