# template pipeline used to deploy bicep code at the rg level

parameters:
  - name: bicepFile
    type: string

stages:
  - stage: CheckOutBicepAndDeploy
    displayName: Deploy Bicep resources
    jobs:
      - deployment: DevDeployBicep
        displayName: Deploy Bicep (Rg level)
        pool:
          vmImage: $(ap_vm_image)
        environment: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: Running ${{ variables.environment }} Deployment
                  inputs:
                    azureSubscription: $(ado_service_connection_rg)
                    scriptType: bash
                    scriptLocation: inlineScript
                    # inlineScript: |
                    #   az --version
                    #   echo "deploying bicep..."
                    #   az deployment sub create \
                    #     --name $(Build.DefinitionName) \
                    #     --location $(location) \
                    #     --template-file $(bicepFile) \
                    #     --parameters location=$(location) prefix=$(namespace) postfix=$(postfix) env=$(environment)
                    inlineScript: |
                      az --version
                      echo "deploying bicep..."
                      az deployment group create \
                        --name $(Build.DefinitionName) \
                        --template-file $(bicepFile) \
                        --parameters location=$(location) prefix=$(namespace) postfix=$(postfix) env=$(environment)
