# template pipeline used to lint bicep code for all arm deployments

parameters:
  - name: bicepFile
    type: string

stages:
  - stage: Lint
    displayName: Lint and Preflight check
    jobs:
      - job: LintBicep
        displayName: Lint Bicep Code
        steps:
          - checkout: self
          - script: |
              az bicep build --file $(bicepFile)
            name: LintBicepCode
            displayName: Run Bicep Linter
