# template pipeline used to validate bicep code for all arm deployments.
# Note that this is valid only at the rg level, which means it will fail if
# you try to create a resource group

parameters:
  - name: bicepFile
    type: string

stages:
  - stage: PreflightValidation
    jobs:
      - job: ValidateBicepCode
        displayName: Validate Bicep Code (Rg level)
        steps:
          - task: AzureCli@2
            name: RunPreflightValidateion
            displayName: Run Preflight Validation
            inputs:
              azureSubscription: $(ado_service_connection_rg)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              # inlineScript: |
              #   az deployment sub validate \
              #   --name $(Build.DefinitionName) \
              #   --template-file $(bicepFile) \
              #   --location $(location) \
              #   --parameters location=$(location) prefix=$(namespace) postfix=$(postfix) env=$(environment)
              inlineScript: |
                az deployment group validate \
                  --resource-group $(resource_group) \
                  --name $(Build.DefinitionName) \
                  --template-file $(bicepFile) \
                  --parameters location=$(location) prefix=$(namespace) postfix=$(postfix) env=$(environment) resource_group=$(resource_group)
