# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-latest

  namespace: mlopstpl #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 4876
  location: westeurope
  environment: prod


  # Azure DevOps
  ado_service_connection_rg: mlopstpl-rg-arm-prod
  ado_service_connection_aml_ws: mlopstpl-mlw-arm-prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)