# app-ci YAML pipeline
resources:
  pipelines:
    - pipeline: artifact-creator
      source: artifact-creator
      trigger: true

trigger: none

jobs:
  - job: Build
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DownloadBuildArtifacts@1
        displayName: "Download"
        inputs:
          buildType: specific
          project: mlops_template
          pipeline: artifact-creator
          specificBuildWithTriggering: true
          artifactName: MyBuildArtifact
          downloadPath: $(System.DefaultWorkingDirectory)/myartifact

      - script: |
          cat $(System.DefaultWorkingDirectory)/myartifact/sample.txt
        displayName: "Display Artifact Contents"
