# app-ci YAML pipeline
resources:
  pipelines:
    - pipeline: artifact-creator # Name of the pipeline resource.
      source: artifact-creator # The name of the pipeline referenced by this pipeline resource.
      trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

trigger: none

jobs:
  - job: Build
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DownloadBuildArtifacts@1
        displayName: "Download"
        inputs:
          buildType: specific
          project: mlops_template
          pipeline: artifact-creator
          buildVersionToDownload: latest
          artifactName: MySampleArtifact
          downloadPath: $(System.DefaultWorkingDirectory)/myartifact

      - script: |
          cat $(System.DefaultWorkingDirectory)/sample.txt
        displayName: "Display Artifact Contents"
