trigger: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: PublishArtifact
    jobs:
      - job: PublishArtifact
        steps:
          - script: |
              echo "This is a sample text file." > $(Build.ArtifactStagingDirectory)/sample.txt
            displayName: "Create sample.txt"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              artifact: "MyBuildArtifact"
            displayName: "Publish sample.txt artifact"
