trigger: none # Manual trigger

stages:
  - stage: Publish
    jobs:
      - job: PublishArtifact
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: |
              echo "Creating sample.txt..."
              echo "This is a sample text file." > $(Build.ArtifactStagingDirectory)/sample.txt
            displayName: "Create sample.txt"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)" # Publish the entire staging directory
              artifact: "MyBuildArtifact" # Give a name to your artifact
            displayName: Push artifacts from Build.ArtifactStagingDirectory
