trigger: none
pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: artifact-creator
      source: artifact-creator
      trigger: true

stages:
  - stage: GetArtifact
    jobs:
      - job: Build
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: "Download Artifact"
            inputs:
              buildType: specific
              project: mlops_template
              pipeline: artifact-creator
              specificBuildWithTriggering: true
              artifactName: MyBuildArtifact
              downloadPath: $(System.DefaultWorkingDirectory)/myartifact

          - script: |
              cat $(System.DefaultWorkingDirectory)/myartifact/sample.txt
            displayName: "Display Artifact Contents"
