variables:
  # - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'main' branch: PRD environment
  #     - template: ../config-infra-prod.yml
  # - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'develop' or feature branches: DEV environment
  #     - template: ../config-infra-dev.yml
  - template: ../config-infra-prod.yml
    bicepFile: "./infrastructure/main.bicep"

trigger:
  - none

pool:
  vmImage: $(ap_vm_image)

stages:
  - template: ./infrastructure/templates/lint-bicep.yml
    parameters:
      bicepFile: $(bicepFile)
  - template: ./infrastructure/templates/validate-bicep-rg-level.yml
    parameters:
      bicepFile: $(bicepFile)
  - template: ./infrastructure/templates/deploy-bicep-rg-level.yml
    parameters:
      bicepFile: $(bicepFile)
