variables:
  # - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'main' branch: PRD environment
  #     - template: ../config-infra-prod.yml
  # - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'develop' or feature branches: DEV environment
  #     - template: ../config-infra-dev.yml
  - template: ../config-infra-prod.yml
  - name: bicepFile
    value: "./infrastructure/main.bicep"

trigger:
  - none

pool:
  vmImage: $(ap_vm_image)

stages:
  - stage: Lint
    displayName: Lint and Preflight check
    template: ../templates/lint-bicep.yml
    parameters:
      bicepFile: $(bicepFile)
  - stage: PreflightValidation
    template: ../templates/validate-bicep-rg-level.yml
    parameters:
      bicepFile: $(bicepFile)
  - stage: CheckOutBicepAndDeploy
    displayName: Deploy Bicep resources
    template: ../templates/deploy-bicep-rg-level.yml
    parameters:
      bicepFile: $(bicepFile)
