variables:
  # - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'main' branch: PRD environment
  #     - template: ../../config-infra-prod.yml
  # - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'develop' or feature branches: DEV environment
  #     - template: ../../config-infra-dev.yml
  - template: ../../config-infra-prod.yml
  - name: endpoint_name
    value: mlopsclass-$(namespace)$(postfix)$(environment)
  - name: endpoint_type
    value: online
  - name: endpoint_file
    value: ./.pipelines/mlops/online/online-endpoint.yml

trigger:
  - none

pool:
  vmImage: $(ap_vm_image)

stages:
  - stage: CreateOnlineEndpoint
    displayName: Create/Update Online Endpoint
    jobs:
      - job: DeployOnlineEndpoint
        steps:
          - checkout: self
          - template: ../../templates/install-aml-cli.yml
          - template: ../../templates/connect-to-workspace.yml
          - template: ../../templates/create-endpoint.yml
            parameters:
              endpoint_file: ${{ variables.endpoint_file }}
          - template: ../../templates/allocate-traffic.yml
            parameters:
              traffic_allocation: mlopsclass-online-dp=100
        # - template: templates/${{ variables.version }}/create-deployment.yml@mlops-templates
        #   parameters:
        #     deployment_name: taxi-online-dp
        #     deployment_file: mlops/azureml/deploy/online/online-deployment.yml
        # - template: templates/${{ variables.version }}/allocate-traffic.yml@mlops-templates
        #   parameters:
        #     traffic_allocation: taxi-online-dp=100
        # - template: templates/${{ variables.version }}/test-deployment.yml@mlops-templates
        #   parameters:
        #     deployment_name: taxi-online-dp
        #     sample_request: data/taxi-request.json
        #     request_type: json
