# check https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?tabs=yaml&view=azure-devops#branch-considerations
# for triggering after training

variables:
  # - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'main' branch: PRD environment
  #     - template: ../../config-infra-prod.yml
  # - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
  #     # 'develop' or feature branches: DEV environment
  #     - template: ../../config-infra-dev.yml
  - template: ../../config-infra-prod.yml
  - name: endpoint_name
    value: mlopsclass-$(namespace)$(postfix)$(environment)
  - name: endpoint_type
    value: online
  - name: endpoint_file
    value: ./.pipelines/mlops/online/online-endpoint.yml
  - name: deployment_name
    value: mlopsclass-online-dp
  - name: deployment_file
    value: ./.pipelines/mlops/online/online-deployment.yml

trigger:
  - none

pool:
  vmImage: $(ap_vm_image)

stages:
  - stage: CreateOnlineEndpoint
    displayName: Create/Update Online Endpoint
    jobs:
      - job: DeployOnlineEndpoint
        steps:
          - checkout: self
          - template: ../../templates/install-aml-cli.yml
          - template: ../../templates/connect-to-workspace.yml
          - template: ../../templates/create-endpoint.yml
            parameters:
              endpoint_file: ${{ variables.endpoint_file }}
          - template: ../../templates/create-deployment.yml
            parameters:
              deployment_name: ${{ variables.deployment_name }}
              deployment_file: ${{ variables.deployment_file }}
          - template: ../../templates/allocate-traffic.yml
            parameters:
              traffic_allocation: ${{ variables.deployment_name }}=100
